name: build-binary

on:
  push:
    # tags:
    #   - "v*.*.*"
    branches:
      - feature/change-builder-to-buitka

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest]
        os: [windows-latest]
        python-version: ['3.9']

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: replace version
        run: |
          from pathlib import Path
          version = [l for l in Path('pyproject.toml').read_text().splitlines() if 'version' in l][0].split(' ')[-1].strip('\"')
          f = Path('src/ntfsdump/models/MetaData.py')
          text = f.read_text().replace("get_version(name)", f"\'{version}\'")
          f.write_text(text)
        shell: python

      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install

      - name: run python
        run: |
          poetry run ntfsdump -h
      
      - name: build for windows
        if: matrix.os == 'windows-latest'
        run: |
          poetry run pip install nuitka zstandard
          poetry run python -m nuitka --onefile --assume-yes-for-downloads -o dist/ntfsdump.exe --module ntfsdump --include-package=some_package

      - name: verify for windows
        if: matrix.os == 'windows-latest'
        run: |
          dist/ntfsdump.exe -h
          dist/ntfsdump.exe -v

      # - name: build for ubuntu
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     poetry run pip install nuitka zstandard
      #     poetry run python -m nuitka --onefile --disable-ccache --follow-imports --assume-yes-for-downloads -o dist/ntfsdump src/ntfsdump/views/NtfsDumpView.py

      # - name: verify for ubuntu
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     dist/ntfsdump -h
      #     dist/ntfsdump -v

      # - name: upload
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: dist/ntfsdump.exe
